config/routes.rb
Rails.application.routes.draw do

  resources :course_options
  #get 'admin/csv_template'
  #get 'admin/generate_csv'
  #get 'admin/download_csv'

  resources :enrollments
  resources :attempt_choices
  resources :teams, param: :name do
    collection {post :import}
  end

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, param: :name do
    collection {post :import}
  end

  get '/import/:model' => 'admin#upload_create'
  get 'users/index'
  root 'users#index'
  resources :quizzes do
    resources :questions
    resources :attempts
    collection {post :import}
  end
  resources :questions do
    resources :choices
    collection {post :import}
  end
  resources :courses
  resources :memberships

  get 'quizzes/:id/leaderboard', to: 'quizzes#leaderboard', as: 'leaderboard'
  get 'quizzes/:id/scores', to: 'quizzes#scores', as: 'scores'
  get 'quizzes/:id/results', to: 'quizzes#results', as: 'results'
  get 'quizzes/:quiz_id/attempts/:attempt_id/students/:user_id', to: 'attempts#show_student', as: 'show_student'
  get 'quizzes/:quiz_id/attempts/:attempt_id/teams/:team_id', to: 'attempts#show_team', as: 'show_team'
  get 'questions/:question_id/students/:student_id', to: 'attempt_choices#show_attempts', as: 'view_attempt_choices'
  get 'questions/:question_id/teams/:team_id', to: 'attempt_choices#show_team_attempts', as: 'view_team_attempt_choices'
  get 'attempts/:id/rescore', to: 'attempts#rescore', as: 'rescore'

  get 'add_member', to: 'memberships#add_member'
  get 'admin_dashboard', to: 'admin#dashboard'
  get 'dashboard', to: 'users#dashboard'
  # get 'download', to: 'admin#download'
  match '/download' => 'admin#index', via: :get, defaults: { format: :csv }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_jumbotron.html.erb
<div class="jumbotron">
  <% if user_signed_in? %>
    <div class="row">
      <div class="col-sm-11">
        <h2><%= link_to current_user.username, dashboard_path %></h2>
      </div>
      <div class="col-sm-1">

      </div>
    </div>

    <hr />
    <div class="row">
        <div class="col-sm-11">
          <h4>
            <% if current_user.team.present? %>
              <%= link_to current_user.team.name, team_path(current_user.team.name) %>
            <% elsif current_user.admin? %>
              <%= link_to "Super Secret Admin Dashboard", admin_dashboard_path, class: 'btn btn-primary' %>
              <%= link_to "Create New Course", new_course_path, class: 'btn btn-primary' %>
              <%= link_to "Create New Quiz", new_quiz_path, class: 'btn btn-primary' %>
            <% end %>
          </h4>
        </div>
        <div class="col-sm-1">

        </div>
    </div>
  <% else %>
    <%= link_to "Login", new_user_session_path, class: 'btn btn-primary btn-lg btn-block' %>
  <% end %>
</div>

app/views/shared/_user_dash.html.erb
<table class="table">
  <tr>
      <th>Quiz</th>
      <th>Due date</th>
      <th>My score</th>
      <th>Team score</th>
  </tr>
    <% @quizzes.each do |quiz| %>
        <tr>
          <td>
            <% if quiz.due_date < Time.now %>
              <% if current_user.admin? || quiz.attempts.where(team_id: current_user.team.id, team_attempt: true).present? %>
                <%= link_to quiz.name, quiz_path(quiz.id), class: "btn btn-sm btn-outline-success" %>
              <% else %>
                <%= link_to quiz.name, quiz_path(quiz.id), class: "btn btn-sm btn-success" %>
              <% end %>
            <% else %>
              <%= link_to quiz.name, quiz_path(quiz.id), class: "btn btn-sm #{duedate_helper(quiz)}" %>
            <% end %>
          </td>
          <td>
            <strong>Due:</strong> <%= duedate(quiz) %>
          </td>
          <td>
            <% if quiz.attempts.where(user_id: current_user.id, team_attempt: false).present? %>
              <%= my_results(quiz) %>
            <% else %>
              Not taken
            <% end %>
          </td>
          <td>
            <% if current_user.admin? %>
              Team quiz
            <% elsif quiz.attempts.where(team_id: current_user.team.id, team_attempt: true).present? %>
              <%= quiz.attempts.where(team_id: current_user.team.id, team_attempt: true).first.points %> / <%= number_to_percentage quiz.attempts.where(team_id: current_user.team.id, team_attempt: true).first.points.to_f / quiz.choices.count.to_f * 100, precision: 0 %>
            <% else %>
              Team quiz not started
            <% end %>
          </td>
        </tr>
    <% end %>
</table>