config/routes.rb
Rails.application.routes.draw do

  resources :course_options
  #get 'admin/csv_template'
  #get 'admin/generate_csv'
  #get 'admin/download_csv'

  resources :enrollments
  resources :attempt_choices
  resources :teams, param: :name do
    collection {post :import}
  end

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, param: :name do
    collection {post :import}
  end

  get '/import/:model' => 'admin#upload_create'
  get 'users/index'
  root 'users#index'
  resources :quizzes do
    resources :questions
    resources :attempts
    collection {post :import}
  end
  resources :questions do
    resources :choices
    collection {post :import}
  end
  resources :courses
  resources :memberships

  get 'quizzes/:id/leaderboard', to: 'quizzes#leaderboard', as: 'leaderboard'
  get 'quizzes/:id/scores', to: 'quizzes#scores', as: 'scores'
  get 'quizzes/:id/results', to: 'quizzes#results', as: 'results'
  get 'quizzes/:quiz_id/attempts/:attempt_id/students/:user_id', to: 'attempts#show_student', as: 'show_student'
  get 'quizzes/:quiz_id/attempts/:attempt_id/teams/:team_id', to: 'attempts#show_team', as: 'show_team'
  get 'questions/:question_id/students/:student_id', to: 'attempt_choices#show_attempts', as: 'view_attempt_choices'
  get 'questions/:question_id/teams/:team_id', to: 'attempt_choices#show_team_attempts', as: 'view_team_attempt_choices'
  get 'attempts/:id/rescore', to: 'attempts#rescore', as: 'rescore'

  get 'add_member', to: 'memberships#add_member'
  get 'admin_dashboard', to: 'admin#dashboard'
  get 'dashboard', to: 'users#dashboard'
  # get 'download', to: 'admin#download'
  match '/download' => 'admin#index', via: :get, defaults: { format: :csv }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attempt_choice.rb
class AttemptChoice < ApplicationRecord
  belongs_to :attempt
  belongs_to :question
  belongs_to :choice
  belongs_to :user
  belongs_to :team, optional: true
  #validates_uniqueness_of :choice, scope: %i[user_id team_id]
  validates_uniqueness_of :choice, scope: %i[team_id attempt_id user_id]
  validates_uniqueness_of :question, scope: %i[attempt_id user_id], if: :individual_attempt?

  def individual_attempt?
    team_id == nil
  end
end

app/controllers/attempt_choices_controller.rb
class AttemptChoicesController < ApplicationController
  before_action :set_attempt_choice, only: [:show, :edit, :update, :destroy]

  # GET /attempt_choices
  # GET /attempt_choices.json
  def index
    @attempt_choices = AttemptChoice.all
  end

  # GET /attempt_choices/1
  # GET /attempt_choices/1.json
  def show
  end

  def show_attempts
    if user_signed_in? && current_user.admin?
      @question = Question.find(params[:question_id])
      @student = User.find(params[:student_id])
      @attempt = @student.attempts.where(quiz_id: @question.quiz_id, team_attempt: false).first
      @attempts = @question.attempt_choices.where(user_id: @student.id)
    else
      redirect_to root_url
    end
  end

  def show_team_attempts
    if user_signed_in? && current_user.admin?
      @question = Question.find(params[:question_id])
      @team = Team.find(params[:team_id])
      @attempt = @team.attempts.where(quiz_id: @question.quiz_id, team_attempt: true).first
      @attempts = @question.attempt_choices.where(team_id: @team.id)
    else
      redirect_to root_url
    end
  end

  # GET /attempt_choices/new
  def new
    @attempt_choice = AttemptChoice.new
  end

  # GET /attempt_choices/1/edit
  def edit
  end

  # POST /attempt_choices
  # POST /attempt_choices.json

  def points_possible(question)
    @total = question.choices.size + 1
    @attempts = current_user.attempt_choices.where(question_id: question.id).size
    @possible = @total - @attempts
  end

  def team_points(question)
    @total = question.choices.size
    puts "total: #{@total}"
    @attempts = current_user.team.attempt_choices.where(question_id: question.id).size - 1
    puts "attempt count: #{@attempts}"
    @possible = @total - @attempts
    puts "possible: #{@possible}"
    if @possible < 1
      @possible = 1
    end
    @possible.to_i
  end

  def create
    @user = User.find(params[:user_id])
    @team = @user.team
    @attempt = Attempt.find(params[:attempt_id])
    if @attempt.points.nil?
      @attempt.points = 0
      @attempt.save
    end
    @choice = Choice.find(params[:choice_id])
    @question = Question.find(params[:question_id])
    @quiz = @question.quiz
    if params[:team_id].present?
      @attempt_choice = AttemptChoice.new(attempt_id: @attempt.id, choice_id: @choice.id, question_id: @question.id, user_id: @user.id, team_id: @team.id)
    else
      @attempt_choice = AttemptChoice.new(attempt_id: @attempt.id, choice_id: @choice.id, question_id: @question.id, user_id: @user.id)
    end

    respond_to do |format|
      if @attempt_choice.save
        if @choice.correct? && @attempt.team_attempt?
          points = @attempt.points + team_points(@question)
          puts "points: #{points}"
          @attempt.points = points
          puts "attempt points: #{@attempt.points}"
          @attempt.save
        elsif @choice.correct?
          points = @attempt.points + 1
          @attempt.points = points
          @attempt.save
        end
        format.html { redirect_to quiz_attempt_path(@quiz.id, @attempt.id), notice: 'Attempt choice was successfully created.' }
        format.json { render :show, status: :created, location: @attempt_choice }
        format.js
      else
        format.html { render :new }
        format.json { render json: @attempt_choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attempt_choices/1
  # PATCH/PUT /attempt_choices/1.json
  def update
    respond_to do |format|
      if @attempt_choice.update(attempt_choice_params)
        format.html { redirect_to @attempt_choice, notice: 'Attempt choice was successfully updated.' }
        format.json { render :show, status: :ok, location: @attempt_choice }
      else
        format.html { render :edit }
        format.json { render json: @attempt_choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attempt_choices/1
  # DELETE /attempt_choices/1.json
  def destroy
    @question = @attempt_choice.question
    @student = @attempt_choice.user
    if @attempt_choice.team_id.present?
      @team_id = Team.find(@attempt_choice.team_id).id
    else
      @team_id = nil
    end

    @attempt = @attempt_choice.attempt
    @attempt.points = 0
    @questions = @attempt.quiz.questions
    if @team_id.present?
      @questions.each do |q|
        p = q.choices.count.to_f - q.attempt_choices.where(team_id: @team_id).count.to_f + 1
        if p < 1
          p = 1
        end
        @attempt.points = @attempt.points + p.to_i
        puts "points: #{@attempt.points}"
        @attempt.save
      end
    else
      @questions.each do |q|
        if q.attempt_choices.where(user_id: @student.id, team_id: nil).first.choice.correct?
          p = 1
        else
          p = 0
        end
        @attempt.points = @attempt.points + p.to_i
        puts "points: #{@attempt.points}"
        @attempt.save
      end
    end

    @attempt_choice.destroy
    respond_to do |format|
      if @team_id.present?
        format.html { redirect_to view_team_attempt_choices_path(@question.id, @team_id), notice: 'Attempt choice was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to view_attempt_choices_path(@question.id, @student.id), notice: 'Attempt choice was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attempt_choice
      @attempt_choice = AttemptChoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attempt_choice_params
      params.require(:attempt_choice).permit(:attempt_id, :question_id, :choice_id, :user_id, :team_id)
    end
end

app/helpers/attempt_choices_helper.rb
module AttemptChoicesHelper
  def correct_confetti
    confetti = ["confetti.gif", "egg.gif", "excellent.gif", "good.gif", "nice.gif", "shark.gif", "sparkle.gif", "stars.gif", "wow.gif", "wow2.gif", "yay.gif", "yes.gif"]
    this_one = confetti.sample
  end
end

app/views/attempt_choices/_form.html.erb
<%= form_with(model: attempt_choice, local: true) do |form| %>
  <% if attempt_choice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attempt_choice.errors.count, "error") %> prohibited this attempt_choice from being saved:</h2>

      <ul>
      <% attempt_choice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :attempt_id %>
    <%= form.text_field :attempt_id, id: :attempt_choice_attempt_id %>
  </div>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.text_field :question_id, id: :attempt_choice_question_id %>
  </div>

  <div class="field">
    <%= form.label :choice_id %>
    <%= form.text_field :choice_id, id: :attempt_choice_choice_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :attempt_choice_user_id %>
  </div>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.text_field :team_id, id: :attempt_choice_team_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/attempt_choices/create.js.erb
<% if @attempt.team_id.nil? %>
  $(".btn-question-<%= @choice.question.id %>").addClass("btn-secondary disabled");
  $("#btn-choice-<%= @choice.id %>").removeClass("btn-secondary btn-outline-primary btn-outline-success btn-outline-info btn-outline-warning btn-outline-danger");
  $("#btn-choice-<%= @choice.id %>").addClass("btn-info disabled");
<% elsif @choice.correct? %>
  $("#points").text("<%= @attempt.points %> Points");
  $(".btn-question-<%= @choice.question.id %>").addClass("btn-secondary disabled");
  $("#btn-choice-<%= @choice.id %>").removeClass("btn-secondary btn-outline-primary btn-outline-success btn-outline-info btn-outline-warning btn-outline-danger");
  $("#btn-choice-<%= @choice.id %>").addClass("btn-success disabled");
  $(".confetti").append('<%= image_tag(correct_confetti, id: "correct-confetti", height: "500", width: "500") %>');
  setTimeout(function(){
    $("#correct-confetti").fadeOut(1000);
  }, 1000);
  setTimeout(function(){
    $("#correct-confetti").remove();
  }, 2000);
<% else %>
  $("#btn-choice-<%= @choice.id %>").addClass("btn-secondary disabled");
  $("#points-<%= @choice.question.id %>").text("<%= team_points_possible(@choice.question) %>");
<% end %>

app/views/attempt_choices/edit.html.erb
<h1>Editing Attempt Choice</h1>

<%= render 'form', attempt_choice: @attempt_choice %>

<%= link_to 'Show', @attempt_choice %> |
<%= link_to 'Back', attempt_choices_path %>

app/views/attempt_choices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attempt Choices</h1>

<table>
  <thead>
    <tr>
      <th>Attempts</th>
      <th>Questions</th>
      <th>Choices</th>
      <th>User</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attempt_choices.each do |attempt_choice| %>
      <tr>
        <td><%= attempt_choice.attempts %></td>
        <td><%= attempt_choice.questions %></td>
        <td><%= attempt_choice.choices %></td>
        <td><%= attempt_choice.user %></td>
        <td><%= attempt_choice.team %></td>
        <td><%= link_to 'Show', attempt_choice %></td>
        <td><%= link_to 'Edit', edit_attempt_choice_path(attempt_choice) %></td>
        <td><%= link_to 'Destroy', attempt_choice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attempt Choice', new_attempt_choice_path %>

app/views/attempt_choices/new.html.erb
<h1>New Attempt Choice</h1>

<%= render 'form', attempt_choice: @attempt_choice %>

<%= link_to 'Back', attempt_choices_path %>

app/views/attempt_choices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Attempts:</strong>
  <%= @attempt_choice.attempts %>
</p>

<p>
  <strong>Questions:</strong>
  <%= @attempt_choice.questions %>
</p>

<p>
  <strong>Choices:</strong>
  <%= @attempt_choice.choices %>
</p>

<p>
  <strong>User:</strong>
  <%= @attempt_choice.user %>
</p>

<p>
  <strong>Team:</strong>
  <%= @attempt_choice.team %>
</p>

<%= link_to 'Edit', edit_attempt_choice_path(@attempt_choice) %> |
<%= link_to 'Back', attempt_choices_path %>

app/views/attempt_choices/show_attempts.html.erb
<h1><%= @question.quiz.name %>:
  <small class="text-muted">
    <%= link_to @student.username, show_student_path(@question.quiz.id, @attempt.id, @student.id) %>
  </small>
</h1>

  <div class="field">

    <div class="row">
      <div class="col-lg-10 col-xs-12">
        <h5><%= @question.body %></h5>

        <ol type="A" class="nowrap">

          <% @question.choices.each do |c, index| %>
                <li><span class="<%= admin_correct_class(c, @attempt) %>"><%= c.choice_body %></span></li>
              <ul><% c.attempt_choices.where(user_id: @student.id, team_id: nil).order(created_at: :asc).each do |attempt| %>
                  <li>
                    <span class="<%='bg-info text-light' if attempt == @question.attempt_choices.where(user_id: @student.id, team_id: nil).order(created_at: :asc).first %>">
                      <%= attempt.created_at.strftime("%r") %> | <%= link_to 'Delete?', attempt_choice_path(attempt.id), method: :delete, data: { confirm: 'Are you sure?' } %>
                    </span>
                  </li>
              <% end %></ul>
              </hr>
          <% end %>

        </ol>
      </div>

    </div>

      <hr />

  </div>

app/views/attempt_choices/show_team_attempts.html.erb
<h1><%= @question.quiz.name %>:
  <small class="text-muted">
    <%= link_to @team.name, show_team_path(@question.quiz.id, @attempt.id, @team.id) %>
  </small>
</h1>

  <div class="field">

    <div class="row">
      <div class="col-lg-10 col-xs-12">
        <h5><%= @question.body %></h5>

        <ol type="A" class="nowrap">

          <% @question.choices.each do |c, index| %>
                <li><span class="<%= admin_correct_class(c, @attempt) %>"><%= c.choice_body %></span></li>
              <ul><% c.attempt_choices.where(team_id: @team.id).order(created_at: :asc).each do |attempt| %>
                  <li>
                    <span class="<%='bg-info text-light' if attempt == @question.attempt_choices.where(team_id: @team.id).order(created_at: :asc).first %>">
                      <%= attempt.user.firstname %>: <%= attempt.created_at.strftime("%r") %> | <%= link_to 'Delete?', attempt_choice_path(attempt.id), method: :delete, data: { confirm: 'Are you sure?' } %>
                    </span>
                  </li>
              <% end %></ul>
              </hr>
          <% end %>

        </ol>
      </div>

    </div>

      <hr />

  </div>