config/routes.rb
Rails.application.routes.draw do

  resources :course_options
  #get 'admin/csv_template'
  #get 'admin/generate_csv'
  #get 'admin/download_csv'

  resources :enrollments
  resources :attempt_choices
  resources :teams, param: :name do
    collection {post :import}
  end

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, param: :name do
    collection {post :import}
  end

  get '/import/:model' => 'admin#upload_create'
  get 'users/index'
  root 'users#index'
  resources :quizzes do
    resources :questions
    resources :attempts
    collection {post :import}
  end
  resources :questions do
    resources :choices
    collection {post :import}
  end
  resources :courses
  resources :memberships

  get 'quizzes/:id/leaderboard', to: 'quizzes#leaderboard', as: 'leaderboard'
  get 'quizzes/:id/scores', to: 'quizzes#scores', as: 'scores'
  get 'quizzes/:id/results', to: 'quizzes#results', as: 'results'
  get 'quizzes/:quiz_id/attempts/:attempt_id/students/:user_id', to: 'attempts#show_student', as: 'show_student'
  get 'quizzes/:quiz_id/attempts/:attempt_id/teams/:team_id', to: 'attempts#show_team', as: 'show_team'
  get 'questions/:question_id/students/:student_id', to: 'attempt_choices#show_attempts', as: 'view_attempt_choices'
  get 'questions/:question_id/teams/:team_id', to: 'attempt_choices#show_team_attempts', as: 'view_team_attempt_choices'
  get 'attempts/:id/rescore', to: 'attempts#rescore', as: 'rescore'

  get 'add_member', to: 'memberships#add_member'
  get 'admin_dashboard', to: 'admin#dashboard'
  get 'dashboard', to: 'users#dashboard'
  # get 'download', to: 'admin#download'
  match '/download' => 'admin#index', via: :get, defaults: { format: :csv }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attempt.rb
class Attempt < ApplicationRecord
  belongs_to :user
  belongs_to :quiz
  belongs_to :team, optional: true
  has_many :attempt_choices
  #validates_uniqueness_of :team
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  before_action :set_attempt, only: [:show, :edit, :update, :destroy]

  # GET /attempts
  # GET /attempts.json
  def index
    if user_signed_in?
      @attempts = Attempt.all
    else
      redirect_to root_url, notice: "Sorry, you need to log in first."
    end
  end

  # GET /attempts/1
  # GET /attempts/1.json
  def show
    if user_signed_in?
      @quiz = Quiz.find(params[:quiz_id])
      @questions = @quiz.questions
      @choices = Choice.joins(:question).merge(@questions).uniq
      @points_possible = @choices.size
      if params[:results].present? && current_user.team.attempts.where(quiz_id: params[:quiz_id]).present?
        @results = true
        @team_attempt = @quiz.attempts.where(team_attempt: true, team_id: current_user.team.id, quiz_id: @quiz.id).first
        @individual_attempt = @quiz.attempts.where(team_attempt: false, user_id: current_user.id, quiz_id: @quiz.id).first
      end
    else
      redirect_to root_url, notice: "Sorry, you need to log in first."
    end
  end

  def show_student
    if user_signed_in? && current_user.admin?
      @quiz = Quiz.find(params[:quiz_id])
      @questions = @quiz.questions
      @choices = Choice.joins(:question).merge(@questions).uniq
      @points_possible = @choices.size
      @student = User.find(params[:user_id])
      @attempt = Attempt.find(params[:attempt_id])
    else
      redirect_to root_url, notice: "Sorry, you need to log in first."
    end
  end

  def rescore
    if user_signed_in? && current_user.admin?
      @attempt = Attempt.find(params[:id])
      @choices = AttemptChoice.where(attempt_id: @attempt.id).all
      @quiz = @attempt.quiz
      @quiz.questions.each do |q|
        attemptchoices = AttemptChoice.where(question_id: q.id, user_id: @attempt.user_id, team_id: nil).all
        attemptchoices.each do |c|
          c.update(attempt_id: @attempt.id)
        end
      end
      @points = 0
      @choices.each do |c|
        if c.choice.correct == true
          @points = @points + 1
          puts "#{@points} + 1"
        else
          @points
        end
      end
      @attempt.update(points: @points)
      redirect_to show_student_path(quiz_id: @attempt.quiz_id, attempt_id: @attempt.id, user_id: @attempt.user_id), notice: "Quiz rescored with #{@points} points."
    else
      redirect_to root_url, notice: "Sorry, you need to log in first."
    end
  end

  def show_team
    if user_signed_in? && current_user.admin?
      @quiz = Quiz.find(params[:quiz_id])
      @questions = @quiz.questions
      @choices = Choice.joins(:question).merge(@questions).uniq
      @points_possible = @choices.size
      @team = Team.find(params[:team_id])
      @attempt = Attempt.find(params[:attempt_id])
    else
      redirect_to root_url, notice: "Sorry, you need to log in first."
    end
  end

  # GET /attempts/new
  def new
    @quiz = Quiz.find(params[:quiz_id])
    @attempt = @quiz.attempts.build
  end

  # GET /attempts/1/edit
  def edit
  end

  # POST /attempts
  # POST /attempts.json
  def create
    @user = current_user
    @team = current_user.team
    @quiz = Quiz.find(params[:quiz_id])
    if params[:team].present?
      @attempt = Attempt.new(user_id: @user.id, quiz_id: params[:quiz_id], team_id: @team.id, team_attempt: true)
    else
      @attempt = Attempt.new(user_id: @user.id, quiz_id: params[:quiz_id], team_id: nil, team_attempt: false)
    end
    respond_to do |format|
      if @attempt.save
        format.html { redirect_to quiz_attempt_path(@quiz.id, @attempt.id), notice: 'Quiz started.' }
        format.json { render :show, status: :created, location: @attempt }
      else
        format.html { render :new, notice: @attempt.errors }
        format.json { render json: @attempt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attempts/1
  # PATCH/PUT /attempts/1.json
  def update
    respond_to do |format|
      if @attempt.update(attempt_params)
        format.html { redirect_to @attempt, notice: 'attempt was successfully updated.' }
        format.json { render :show, status: :ok, location: @attempt }
      else
        format.html { render :edit }
        format.json { render json: @attempt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attempts/1
  # DELETE /attempts/1.json
  def destroy
    @attempt.destroy
    respond_to do |format|
      format.html { redirect_to attempts_url, notice: 'Quiz attempt was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attempt
      @attempt = Attempt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attempt_params
      params.require(:attempt).permit(:user_id, :team_id, :quiz_id, :team_attempt, :points)
    end
end

app/helpers/attempts_helper.rb
module AttemptsHelper
  def outline_button
    @outline_button_classes = ["btn-outline-primary", "btn-outline-success", "btn-outline-info", "btn-outline-warning", "btn-outline-danger", "btn-outline-primary", "btn-outline-success", "btn-outline-info", "btn-outline-warning", "btn-outline-danger", "btn-outline-primary", "btn-outline-success", "btn-outline-info", "btn-outline-warning", "btn-outline-danger", "btn-outline-primary", "btn-outline-success", "btn-outline-info", "btn-outline-warning", "btn-outline-danger", "btn-outline-primary", "btn-outline-success", "btn-outline-info", "btn-outline-warning", "btn-outline-danger", "btn-outline-primary", "btn-outline-success", "btn-outline-info", "btn-outline-warning", "btn-outline-danger", "btn-outline-primary", "btn-outline-success", "btn-outline-info", "btn-outline-warning", "btn-outline-danger"]
  end

  def individual_points_possible(question)
    @total = question.choices.size.to_s
  end

  def individual_points(question)
    if current_user.attempt_choices.where(question_id: question.id, team_id: nil).present?
      @try = current_user.attempt_choices.where(question_id: question.id, team_id: nil).first
      @choice = @try.choice
      if @choice.correct?
        1
      else
        0
      end
    else
      0
    end
  end

  def team_points(question)
    @total = question.choices.count
    @attempts = current_user.team.attempt_choices.where(question_id: question.id).count
    @possible = @total - @attempts + 1
    @possible.to_s
  end

  def team_points_possible(question)
    @total = question.choices.size
    @attempts = current_user.team.attempt_choices.where(question_id: question.id).count
    @possible = @total - @attempts
    @possible.to_s
  end

  def score_points(question)
    @total = question.choices.size
    @attempts = current_user.attempt_choices.where(question_id: question.id).where(team_id: nil).size
    @possible = @total - @attempts + 1
  end

  def correct_class(choice, attempt)
    if attempt.team_attempt? && choice.correct? && attempt.team_id.present?
      "btn-success"
    elsif choice.attempt_choices.where(user_id: current_user.id).present? && attempt.team_attempt == false
      "btn-info"
    elsif choice.correct? && attempt.team_id.present?
      "btn-success"
    else
      "btn-secondary"
    end
  end

  def admin_correct_class(choice, attempt)
    if choice.correct?
      "btn-success"
    else
      "btn-secondary"
    end
  end

  def results_helper(choice)
    if choice.attempt_choices.where(user_id: current_user.id).where(team_id: nil).present?
      if choice.correct?
        '<span class="badge badge-info response">✓</span></br>'.html_safe
      else
        '<span class="badge badge-danger response">X</span></br>'.html_safe
      end
    end
  end

  def admin_helper(choice, student)
    if choice.attempt_choices.where(user_id: student.id).where(team_id: nil).present?
      if choice.correct?
        '<span class="badge badge-info response">✓</span></br>'.html_safe
      else
        '<span class="badge badge-danger response">X</span></br>'.html_safe
      end
    end
  end

  def results_warning_helper(choice)
    if choice.correct? == false
      if choice.attempt_choices.count.to_f >= (choice.quiz.course.users.count.to_f / 5)
        'table-danger'
      end
    end
  end

end

app/views/attempts/_form.html.erb
<%= form_with(model: [@quiz, attempt], local: true) do |form| %>
  <% if attempt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attempt.errors.count, "error") %> prohibited this attempt from being saved:</h2>

      <ul>
      <% attempt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <ol type="1">
    <% @quiz.questions.each do |q| %>
    <div class="row">
      <div class="col-lg-10 col-xs-12">
        <li class="h5"><%= q.body %></li>
        <ol type="A" class="nowrap">

          <%= render partial: "quizzes/choices", locals: {q: q, attempt: attempt} %>

        </ol>
      </div>

      <% if @results.present? || attempt.team_attempt? == false %>
      <div class="col-md-1 individual alert alert-secondary d-none d-sm-none d-md-none d-lg-block">
        <% if @results.present? && %>
          My Points <hr />
          <%= individual_points(q) %>
        <% elsif attempt.team_attempt? == false %>
          Points possible <hr />
          <p id="individual-points-<%= q.id %>">
            1
          </p>
        <% end %>
      </div>
      <% end %>

      <% if @results.present? || attempt.team_attempt? %>
      <div class="col-md-1 team alert alert-primary d-none d-sm-none d-md-none d-lg-block">
        <% if @results.present? %>
          Team Points <hr />
          <%= team_points(q) %>
        <% elsif attempt.team_attempt? %>
          Points possible <hr />
          <p id="points-<%= q.id %>">
            <%= team_points_possible(q) %>
          </p>
        <% end %>
      </div>
      <% end %>

    </div>

      <hr />
    <% end %>
    </ol>
  </div>

  <!-- <div class="actions">
    <%= form.submit 'Submit quiz', class: "btn btn-primary btn-lg" %>
  </div> -->
<% end %>

app/views/attempts/edit.html.erb
<h1>Editing attempt</h1>

<%= render 'form', attempt: @attempt %>

<%= link_to 'Show', @attempt %> |
<%= link_to 'Back', attempts_path %>

app/views/attempts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>attempts</h1>

<table class="counter-table">
  <thead>
    <tr>
      <th>User</th>
      <th>Team</th>
      <th>Quiz</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attempts.each do |attempt| %>
      <tr>
        <td><%= attempt.user %></td>
        <td><%= attempt.team %></td>
        <td><%= attempt.quiz %></td>
        <td><%= link_to 'Show', attempt %></td>
        <td><%= link_to 'Edit', edit_attempt_path(attempt) %></td>
        <td><%= link_to 'Destroy', attempt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New attempt', new_attempt_path %>

app/views/attempts/new.html.erb
<h1><%= @quiz.name %></h1>
<p class="lead"><%= @quiz.description %></p>

<%= render 'form', attempt: @attempt %>

app/views/attempts/show.html.erb
<h1><%= @quiz.name %>:
  <small class="text-muted">
    <% if @results.present? %>
      Results
    <% elsif @attempt.team_attempt? %>
      Team attempt
    <% else %>
      Individual attempt: You only get one chance at each question, and the system won't tell you if your selection is correct until after your team takes the quiz.  Choose wisely!
    <% end %>
  </small>
</h1>
<div class="confetti sticky-top text-center"></div>

<% if @results.present? %>
  <h3 class="alert alert-success sticky-top">My points: <%= @individual_attempt.points %> (<%= number_to_percentage @individual_attempt.points.to_f / @quiz.questions.count.to_f * 100, precision: 0 %>)<% if @team_attempt.present? %> | Team points: <%= @team_attempt.points %> (<%= number_to_percentage @team_attempt.points.to_f / @points_possible.to_f * 100, precision: 0 %> )<% end %></h3>
<% elsif @attempt.team_attempt? %>
  <h3 id="points" class="alert alert-success sticky-top"><%= pluralize @attempt.points, 'Points' %></h3>
<% else %>
  <h3 class="alert alert-success sticky-top"><%= pluralize @attempt.quiz.questions.count, 'Points' %> possible</h3>
<% end %>

<%= render 'form', attempt: @attempt %>

<div class="text-center">
  <% if @attempt.team_attempt? %>
    <%= link_to "Quiz Leaderboard", leaderboard_path(@quiz), class: "btn btn-lg btn-primary" %>
    <%= link_to "View My Results", quiz_attempt_path(@quiz.id, current_user.team.attempts.first.id, results: true), class: "btn btn-lg btn-primary" %>
  <% else %>
    <%= link_to "Start Team Quiz", quiz_path(@quiz), class: "btn btn-lg btn-primary" %>
  <% end %>
</div>

app/views/attempts/show_student.html.erb
<h1><%= @quiz.name %>:
  <small class="text-muted">
    <%= @student.username %> individual results
  </small>
</h1>

<h3 class="alert alert-success sticky-top"><%= @attempt.points %> correct | <%= pluralize @attempt.quiz.questions.count, 'Points' %> possible <%= link_to "Rescore", rescore_path(@attempt.id), class: "btn btn-secondary btn-lg" %></h3>

  <div class="field">
    <ol type="1">
    <% @quiz.questions.each do |q| %>
    <div class="row">
      <div class="col-lg-10 col-xs-12">
        <li class="h5"><%= q.body %></li>
        <% if q.attempt_choices.where(user_id: @student.id, team_id: nil).count > 1 %>
          <span class="alert-danger">This question has <%= pluralize q.attempt_choices.where(user_id: @student.id, team_id: nil).count, "attempt" %>.  <%= link_to "Delete?", view_attempt_choices_path(q.id, @student.id) %></span>
        <% end %>
        <ol type="A" class="nowrap">

          <% q.choices.each do |c, index| %>
            <div class="response-wrapper">
                <%= admin_helper(c, @student) %>
                <li id="btn-choice-<%=c.id%>" class="btn btn-lg btn-answer <%= admin_correct_class(c, @attempt) %> btn-question-<%=q.id%>"><%= c.choice_body %></li>
              </div>
          <% end %>

        </ol>
      </div>

    </div>

      <hr />
    <% end %>
    </ol>
  </div>

app/views/attempts/show_team.html.erb
<h1><%= @quiz.name %>:
  <small class="text-muted">
    <%= @team.name %> team results
  </small>
</h1>

<h3 class="alert alert-success sticky-top"><%= @attempt.points %> correct | <%= pluralize @attempt.quiz.choices.count, 'Points' %> possible</h3>

  <div class="field">
    <ol type="1">
    <% @quiz.questions.each do |q| %>
    <div class="row">
      <div class="col-lg-10 col-xs-12">
        <li class="h5"><%= q.body %></li>
        <% if q.attempt_choices.where(team_id: @team.id).count > 1 %>
          <span class="alert-danger">This question has <%= pluralize q.attempt_choices.where(team_id: @team.id).count, "attempt" %>.  <%= link_to "Delete?", view_team_attempt_choices_path(q.id, @team.id) %></span>
        <% end %>
        <ol type="A" class="nowrap">

          <% q.choices.each do |c, index| %>
            <div class="response-wrapper">
                <%= admin_helper(c, @team) %>
                <li id="btn-choice-<%=c.id%>" class="btn btn-lg btn-answer <%= admin_correct_class(c, @attempt) %> btn-question-<%=q.id%>"><%= c.choice_body %></li>
              </div>
          <% end %>

        </ol>
      </div>

    </div>

      <hr />
    <% end %>
    </ol>
  </div>